airflow_dag_path: '/home/ubuntu/image_airflow_dbt/rd-da-dw-dbt-etl/dags'
config_dag: '/home/ubuntu/image_airflow_dbt/rd-da-dw-dbt-etl/config_json/'
template_path: '/home/ubuntu/image_airflow_dbt/rd-da-dw-dbt-etl/generate_dag/template/'

docker_dbt_path: '/opt/airflow/dbt/rd-da-dw-dbt-etl'
docker_dags_path: '/opt/airflow/dags/rd-da-dw-dbt-etl'
docker_dags_logs: '/opt/airflow/logs'
docker_delete_command: 'docker exec -u root -i image_airflow_dbt_airflow-webserver_1 bash -c'
docker_command: 'docker exec -i  image_airflow_dbt_dbt-container_1 bash -c'



