airflow_dag_path: '/opt/airflow/dags'
config_dag: '/opt/generate_dag/config_json/'
template_path: '/opt/generate_dag/template/'

docker_dbt_path: ''
docker_dags_path: '/opt/airflow/dags'
docker_dags_logs: '/opt/airflow/logs'
docker_delete_command: ['docker exec -u root -i image_airflow_dbt_airflow-webserver_1 bash -c']
docker_command: 'docker exec -i  image_airflow_dbt_dbt-container_1 bash -c'
