airflow_dag_path: '/airflow/dags'
config_dag: '/airflow/config_json/'
template_path: '/airflow/generate_dag/template/'
dbt_path: '/dbt'

repositorio: '/opt/airflow/dags/rd-da-dw-dbt-etl'
dags_logs: '/opt/airflow/logs'