airflow_dag_path: '/airflow/dags'
config_dag: '/airflow/config_json/'
template_path: '/airflow/generate_dag/template/'
dbt_path: '/dbt'

docker_dbt_path: ''
docker_dags_path: ''
docker_dags_logs: '/airflow/logs'
docker_delete_command: 'echo teste'
docker_command: ''
