version: 2

models:
  - name: dbt_clean_orders
    schema: dbt_refined
    description: contem descricao de vendas
    columns:
      - name: order_id
        data_type: INT
        description: Código de ordem
        tests:
          - unique
          - not_null

  - name: dbt_post_hook
    schema: dbt_refined
    description: contem descricao de vendas
    columns:
      - name: order_id
        data_type: INT
        description: Código de ordem
        tests:
          - unique
          - not_null